### ISSUE TITLE
Allow multiple solutions for a single puzzle

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#16]
Just some thoughts looking at the latest commits... before too much work is going into the puzzle backend code.

I'm actually working on a puzzle (first alpha version should be ready soon) which would be composed of multiple very simple subpuzzles (ATM something like 3 but I envision 6-10). My current idea would be that for the given puzzle name you can input multiple solutions, and each would give some small amount of points.

I can of course rework the puzzle to work in some other way, for example I can probably make the subpuzzles results each be a hint to a final solution, however this IMO does not motivate the teams to explore the full puzzle.

I.e., for each puzzle there would be a number of solutions, and their list and the frontend code should print how many are still left unsolved after a successful subpuzzle solution.

**Comment by mfrodl** [comment]
Here is my proposed new database schema (simplified 😃). Basically, we create a new model/table Solution which will be in a many-to-one relationship with Puzzle. It will itself hold the information about the number of points the team can earn by finding the solution.

![quickdbd-export 1](https://user-images.githubusercontent.com/12383572/51895489-88ea9c00-23aa-11e9-920c-a9ad21a005fd.png)

The question is, when can such a puzzle be considered 'solved' (e.g. for purposes of the map icons, see https://github.com/mfrodl/kolecko/issues/10#issuecomment-457386862)? When all solutions have been submitted? When any solution has been submitted? Or we can get rid of the 'solvedness' altogether and just award the points.

**Comment by KoleckoOrg** [comment]
The scheme looks reasonable IMO. 

Regarding the solvedness, I would probably mark it solved after all the subpuzzles are done. In my case it will be a side puzzle anyway, therefore not crucial to solve (and I don't expect teams to solve it fully).

It would be nice to show after inserting an answer, how many unsolved subpuzzles are left. Alternatively it could be shown at the beginning of the puzzle how many subpuzzles it has.
