### ISSUE TITLE
Add support for notifications

### ISSUE THREAD

**Issue by mfrodl** [mfrodl/kolecko#22]
Implement a simple mailbox-like interface which will allow teams to receive real-time notifications, such as:

* New hint received
* New hint request created for puzzle the team has already solved
* New puzzle opened
* Ad hoc instructions from organizers

**Comment by KoleckoOrg** [comment]
Tthe last part is definitelly working, dunno about the first three?

**Comment by KoleckoOrg** [comment]
All done.
