### ISSUE TITLE
Hint improvements

### ISSUE THREAD

**Issue by mfrodl** [mfrodl/kolecko#23]
- [x] When a team creates a new hint request, it must put a bounty on it.
- [x] We have to make sure the point balance is always non-negative. <s>Points put as a bounty need to be somehow 'frozen', making them unavailable for as long as the hint request is open.</s>
- [x] Subtract bounty points from requesting team immediately upon creation.
- [x] Restore bounty points when request cancelled.
- [x] Only allow cancelling of hint requests without opened hints.
- [x] Allow at most one hint request per visit to be opened at a time
- [x] Allow at most one hint per hint request to be opened.
- [x] A hint request cannot be edited in order to guarantee equal conditions for all teams. However, it is possible to close it (without marking an accepted hint) and open a new one for the same puzzle.
- [x] Send 33% of bounty to hint author when a hint is opened.
- [x] Send the remaining points to author when hint accepted.
- [x] To make sure the bounty will be awarded, the app should disallow submitting answers to a puzzle for which the team opened at least one hint but accepted none.
- [x] Similarly, all opened hints have to be star-rated before submitting answers.
- [x] Close hint request when a hint opened (and rated?)
- [x] Hints should be anonymous, i.e. the receiving team shouldn't know the name of the sending team but only an anonymized statistic, such as the average helpfulness or proportion of accepted hints sent by the team.
- [ ] Freeze hint rating once an answer has been submitted.

**Comment by KoleckoOrg** [comment]
We now track all remaining issues in separate bug reports.
