### ISSUE TITLE
Apply the new mobile style only on touch devices

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#28]
Dunno if this is still a work in progress but I don't like being served the new mobile style on my desktop. Can we place the new style into something like @media (hover: none) {} or  media (pointer: coarse) {}, or combination?

I can do this sometime next week if there is no more ongoing work in this area, as this is IMO quite simple frontend change, just hide the new css stuff into the aforementioned block and dig up the old styles from git history...

**Comment by mfrodl** [comment]
Yes, the current look is meant as temporary and the web should definitely be more desktop-friendly.

I would prefer not to go all the way back CSS-wise, though. Would it be sufficient for desktops to e.g. always show the menu and shift the main content appropriately to the right (to avoid overlay)? Here's an example of what it could look like:

![screenshot from 2019-02-10 10-45-26](https://user-images.githubusercontent.com/12383572/52532200-0f936780-2d21-11e9-9a92-27f93d217772.png)

**Comment by KoleckoOrg** [comment]
> Would it be sufficient for desktops to e.g. always show the menu and shift the main content appropriately to the right (to avoid overlay)?

This is perfectly reasonable. Very good job. I would probably not bother with stuff like the menu icons, however I must admit it looks nice :-)
