### ISSUE TITLE
Beeping puzzle search

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#29]
This is not a special puzzle per se but rather a special means of a delivery of any puzzle.

The teams will receive a message with a very imprecise location description (e.g. town part or park, or something like that) with instructions to check the app for more detail when there. While in the specific location, the app will start to beep in regular intervals, based on the distance to the actual puzzle position. 

Specifically this means:
- [ ] When the teams receive the massage start a JavaScript timer which regularly checks if the teams are in the wide area and download the coordinates of the beeping area (probably a circle with given diameter around 100-200m and a center with the puzzle) and the puzzle
- [ ] If they are in, start beeping in intervals based on the actual distance to the puzzle.
- [ ] Stop the beeping when the puzzle code is entered into the system, e.g., each puzzle should allow to specify a specific callback function when it is found (its code inserted into the system) or solved (solution is inserted).

Based on some testing we can tweak whether we should also show the beeping interval on the screen, as evaluation of the interval speed only by ears could be difficult.

**Comment by KoleckoOrg** [comment]
This is actually not a critical feature for the game, I would do this only after all the core (hints, puzzles reporting/teams messaging) stuff is implemented...

**Comment by mfrodl** [comment]
> This is actually not a critical feature for the game, I would do this only after all the core (hints, puzzles reporting/teams messaging) stuff is implemented...

Sounds exactly like my internal definition of <kbd>should have</kbd>. :-) Updating the label.

**Comment by KoleckoOrg** [comment]
This feature was canceled in the meantime
