### ISSUE TITLE
Registration page improvements

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#35]
There are several problems with the registration page:

- [x] it does not check whether the passwords are the same.
- [x] it does not check whether the passwords are empty (I don't in fact care if teams chose a blank password, however if you create a team with blank password ATM you are unable to login later).
- [ ] it shoudl check that at least one player name is not empty.
- [ ] it should check that at least one email field is not empty.

**Comment by mfrodl** [comment]
Password validation added in latest commit; player name and email checking yet to be fixed.
