### ISSUE TITLE
Disable the registration for now

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#38]
We definitelly need to announce the game as the date is now in three and a half month. For this I want to send email to the old participants and post it on kalendar.sifrovacky.cz

I was hoping to have the registration working when we announce the game, however the system is not yet ready, therefore it might be better to take another approach, i.e., to disable the registration for now and place a statement that it will start at some fixed date (middle of June or July might be reasonable). This will buy us some time to get the system in a better shape and since the rest of the (non game) pages is more or less ready, this will allow us to start advertising the game right now, so people have time to plan for it...

In practice, we probably don't need to hide the registration form, it just needs to:
- [ ] add a statement that the registration will start at the given date at the top of the registration form (I can do this after we agree on the date)
- [ ] make any registration attempt fail (Fredy, this is probably your task)

**Comment by mfrodl** [comment]
Are we currently blocked by anything else than #39? If not, I can hopefully make it work by the end of the week (maybe even today or tomorrow) and we can make the announcement right away.

**Comment by KoleckoOrg** [comment]
Actually not, you were very fast with fixing all the issues. There is nothing besides #39 (and #37 where we go with the easy option). Fix the rest and I'll prepare the announcement email...

**Comment by mfrodl** [comment]
@KoleckoOrg, I implemented #39. It's not super polished but will hopefully suffice for now. Could you test it a bit and let me know?

**Comment by KoleckoOrg** [comment]
It should be OK. I found few nitpicks, but no more blockers, I'll fill a new bugs.
