### ISSUE TITLE
Fix kolecko.sifrovacky.cz

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#40]
Shows "502 Bad Gateway - nginx" for unknown reasons.

**Comment by mfrodl** [comment]
Looking into this.

**Comment by mfrodl** [comment]
Should be fixed in https://github.com/mfrodl/kolecko/commit/6e1dfd0f2360ae0144ed8631024e7f4fc3ee1db9.

**Comment by mfrodl** [comment]
Reopening, problem not quite fixed yet.

**Comment by mfrodl** [comment]
Now definitively fixed.
