### ISSUE TITLE
Possible to accept hint multiple times

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#54]
Ask for a hint and then wait till you get one. Then click on open to show it and click immediately on accept. Nothing visibly happens (the accept link is still there) but the points are still added. You can do this mutiple times. To see the accepted status (and for the accept text to disappear) you need to go to other page (or reload).

**Comment by KoleckoOrg** [comment]
Therefore easy solution might be to force page reload on showing hint.

**Comment by mfrodl** [comment]
Accepting hints is now disabled (we don't need it anymore if we assign points based on the rating, right?). Moreover, submitting a star rating will now force page reload.

**Comment by KoleckoOrg** [comment]
Yeah, seems to work fine, but I just tested very briefly.
I'll do more checking either in the lunch break or in the evening and eventually close all the bugs.

**Comment by KoleckoOrg** [comment]
This works now, there is some fallout from the rework which needs fixing, but I can do that on my own.
