### ISSUE TITLE
It is possible to place two hint_requests for a single visit

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#76]
I thought this is already handled somewhere, but seems like it is not.

**Comment by mfrodl** [comment]
We need to allow multiple hint requests in case the first one does not help the team solve the puzzle. Previously, the team had to cancel the first request in order to be able to open an additional one. What would the conditions for allowing a new hint request be now?

**Comment by KoleckoOrg** [comment]
Sorry I was not clear.
It is possible to place a new hint request while the old one is still open. OFC you should be able to place a new request after the old one was closed (and was not helpful). However ATM you can have multiple opened at the same time.

**Comment by KoleckoOrg** [comment]
Wrong button

**Comment by KoleckoOrg** [comment]
Fixed with add51c99658a70fa9f6c19d43f3900ff2c2753ae
