### ISSUE TITLE
Tweak the hint request notification

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#77]
Currently all teamd which solved some puzzle are notified of a new hint request for the specific puzzle even when they are not able to send a hint do to
- they already send a hint before for this same puzzle to this same team
- they send already two hints for this puzzle to any team

**Comment by mfrodl** [comment]
Sorry, will fix.

**Comment by mfrodl** [comment]
Consider the following scenario:
* Team A opens a hint request for certain puzzle
* Teams B and C both send a hint
* Team A opens the hint from Team C
* Team A then creates a new hint request

In this case, Team B can see the new request in the queue, even though _they already sent a hint before for this same puzzle to this same team_.

Seeing that this contradicts your first point, how should the rule be rephrased to make it true? Does the sent hint also have to be opened?

**Comment by mfrodl** [comment]
> Seeing that this contradicts your first point, how should the rule be rephrased to make it true? Does the sent hint also have to be opened?

If this is the case, the behaviour should be fixed in b13c145.

**Comment by KoleckoOrg** [comment]
Sorry, yeah the system is quite complicated. 
My first points should be clearer, instead of:
- they already send a hint before for this same puzzle to this same team
- they already send a hint before for this same puzzle to this same team which was opened.

The same for the point two, only opened hints count to the limit of 2...
I'm not sure how the logic is implemented ATM, while looking at the commit it seems like all hints count to the limit of 2 not only the opened ones, but my code reading skill are super low ATM after rough a night in a bus. I'll try to do some testing, reopening for now.
